---
wildfly_systemd_user: 'wildfly'
wildfly_systemd_group: "{{ wildfly_systemd_user }}"
wildfly_systemd_version: '40.0.0.Final'
wildfly_systemd_install_workdir: '/opt/wildfly/'
wildfly_systemd_home: "{{ wildfly_systemd_install_workdir }}wildfly-{{ wildfly_systemd_version }}/"
wildfly_systemd_config_base: 'standalone.xml'
wildfly_systemd_config_custom_file: ''

wildfly_systemd_port_range_offset: 0
wildfly_systemd_java_version: 21
wildfly_systemd_java_package_name: "{{ 'java-1.8.0-openjdk' if wildfly_systemd_java_version | string == '1.8' else 'java-' + wildfly_systemd_java_version | string + '-openjdk-headless' }}"
wildfly_systemd_java_opts: '-Xmx1024M -Xms512M'

wildfly_systemd_unit_enabled: true
wildfly_systemd_require_privilege_escalation: true
wildfly_systemd_service_config_location: '/etc/systemd/system'
wildfly_systemd_service_config_file_suffix: '.service'
wildfly_systemd_conf_file_suffix: '.conf'
wildfly_systemd_service_config_file_template: 'templates/wfly.service.j2'
wildfly_systemd_service_config_file_template_conf: 'templates/wfly.conf.j2'
wildfly_systemd_service_config_file_location: '/etc/sysconfig'

wildfly_systemd_service_systemd_env_file: "{{ wildfly_systemd_service_config_file_location }}/{{ wildfly_systemd_service_name }}{{ wildfly_systemd_conf_file_suffix }}"
wildfly_systemd_service_systemd_file: "{{ wildfly_systemd_service_config_location }}/{{ wildfly_systemd_service_name }}{{ wildfly_systemd_service_config_file_suffix }}"
wildfly_systemd_enable_yml_config: false
wildfly_systemd_yml_configs: []
wildfly_systemd_yml_configs_repository: ''
wildfly_systemd_jboss_cli_path: "{{ wildfly_systemd_home }}//bin/jboss-cli.sh"
wildfly_systemd_jboss_cli_controller_host: "{{ wildfly_systemd_bind_addr_management }}"
wildfly_systemd_jboss_cli_deploy_force: '--force'
wildfly_systemd_jboss_cli_timeout_value: 5
wildfly_systemd_jboss_cli_timeout: "--timeout={{ wildfly_systemd_jboss_cli_timeout_value * 1000 }}"
wildfly_systemd_jboss_cli_command_prefix: "--connect {{ wildfly_systemd_jboss_cli_timeout }}"

wildfly_systemd_bind_addr: '0.0.0.0'
wildfly_systemd_bind_addr_private: '127.0.0.1'
wildfly_systemd_bind_addr_management: '127.0.0.1'
wildfly_systemd_multicast_addr: '230.0.0.4'

wildfly_systemd_statistics_enabled: false

wildfly_systemd_instance_name: 'wildfly'
wildfly_systemd_node_id: "{{ inventory_hostname_short }}"
wildfly_systemd_service_name: "{{ wildfly_systemd_instance_name }}"
wildfly_systemd_basedir_prefix: "{{ wildfly_systemd_home }}"

wildfly_systemd_pidfile_homedir: "/run/{{ wildfly_systemd_instance_name }}"
wildfly_systemd_selinux_enabled: false

wildfly_systemd_wait_port: 9990
wildfly_systemd_startup_message_id: 'WFLYSRV0025'
wildfly_systemd_wait_for_timeout: 60
wildfly_systemd_wait_for_delay: 10
wildfly_systemd_wait_for_port: "{{ wildfly_systemd_enable_yml_config }}"
wildfly_systemd_wait_for_log: false
