---
galaxy_info:
  role_name: wildfly_snapshot
  namespace: middleware_automation
  author: Ranabir Chakraborty
  description: WildFly configuration snapshot and rollback management
  company: Red Hat, Inc.

  license: GPL-2.0-only

  min_ansible_version: "2.16"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"

  galaxy_tags:
    - java
    - jboss
    - wildfly
    - cli
    - server
    - snapshot
    - rollback
