---
- name: "Load metadata on migration tool full path."
  ansible.builtin.stat:
    path: "{{ wildfly_migration_server_tool_path_to_script }}"
  register: wildfly_migration_migration_tool_state

- name: "Check that path to migration tool is valid."
  ansible.builtin.assert:
    that:
      - wildfly_migration_migration_tool_state is defined
      - wildfly_migration_migration_tool_state.stat is defined
      - wildfly_migration_migration_tool_state.stat.exists is defined
      - wildfly_migration_migration_tool_state.stat.exists
      - wildfly_migration_migration_tool_state.stat.isreg is defined
      - wildfly_migration_migration_tool_state.stat.isreg
    quiet: true
    fail_msg: "Invalid path to migration tool: {{ wildfly_migration_server_tool_path_to_script }}."

- name: "Ensure all files belong to the appropriate owner"
  ansible.builtin.file:
    path: "{{ folder }}"
    recurse: true
    owner: "{{ wildfly_migration_user }}"
    group: "{{ wildfly_migration_group }}"
  changed_when: false
  loop:
    - "{{ previous_wildfly_home }}"
    - "{{ target_wildfly_home }}"
    - "{{ wildfly_migration_server_tool_home }}"
  loop_control:
    loop_var: folder
  when:
    - not wildfly_migration_skip_file_ownership_check is defined
    - wildfly_migration_user is defined and wildfly_migration_user | length > 0
    - wildfly_migration_group is defined and wildfly_migration_group | length > 0
