namespace: middleware_automation
name: wildfly
version: "0.0.7"
readme: README.md
authors:
  - Romain Pelisse <belaran@redhat.com>
  - Andrew Block <ablock@redhat.com>
  - Harsha Cherukuri <hcheruku@redhat.com>
description: Enable Ansible to provisioning JBoss EAP or Wildfly instances.
license_file: "LICENSE"
tags:
  - java
  - jboss
  - wildfly
  - cli
  - server
dependencies:
  middleware_automation.redhat_csp_download: '>=1.1.2'
repository: https://github.com/ansible-middleware/wildfly
documentation: https://github.com/ansible-middleware/wildfly
homepage: https://github.com/ansible-middleware/wildfly
issues: https://github.com/ansible-middleware/wildfly/issues
