---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - molecule/default/vars.yml
  collections:
    - middleware_automation.wildfly
  tasks:
    - name: "TODO"
      ansible.builtin.include_role:
        name: wildfly_validation
      vars:
        wildfly_service_name: wildfly
