---
wildfly_app_deploy_deployment_file: '/path/to/your/application.war'
wildfly_app_deploy_name: 'application.war'
wildfly_app_deploy_jboss_cli_controller_host: 'localhost'
wildfly_app_deploy_jboss_cli_controller_port: '9990'
wildfly_app_deploy_port_range_offset: 0
wildfly_app_deploy_user: "{{ wildfly_user | default('wildfly') }}"
wildfly_app_deploy_group: "{{ wildfly_group | default(wildfly_app_deploy_user) }}"
wildfly_app_deploy_home: "{{ wildfly_install_home }}"
