---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - rhn_username is defined
      - rhn_password is defined
      - wildfly_install_local_path_to_archive is defined
    quiet: true

- name: "Download JBoss EAP from Unified Downloads"
  ansible.builtin.include_role:
    name: wildfly_utils
    tasks_from: download_from_rhn.yml
  vars:
    wildfly_utils_zipfile_dest: "{{ wildfly_install_local_path_to_archive }}"
    eap_utils_product_category: "{{ eap_install_product_category }}"
    eap_utils_archive_filename: "{{ eap_install_archive_filename }}"
    eap_utils_version: "{{ eap_install_version }}"
