---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - rhn_id_file is defined
      - rhn_username is defined
      - rhn_password is defined
      - local_path_to_archive is defined
    quiet: true

- name: "Download JBoss EAP from RHN (id: {{ rhn_id_file }})"
  ansible.builtin.include_role:
    name: jboss_eap
    tasks_from: download_from_rhn.yml
  vars:
    zipfile_dest: "{{ local_path_to_archive }}"
