---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - wildfly_install.download_url is defined
      - wildfly_install.home is defined
      - wildfly_install.archive_name is defined
      - wildfly_install.user is defined
      - wildfly_install.group is defined
      - full_path_to_archive is defined
    quiet: true

- name: "Download Wildfly zipfile from {{ wildfly_install.download_url }} into {{ local_path_to_archive }}"
  delegate_to: localhost
  run_once: true
  ansible.builtin.get_url:
    url: "{{ wildfly_install.download_url }}"
    dest: "{{ local_path_to_archive }}"
