---
- name: "Uninstall Wildlfy from target"
  hosts: instance
  gather_facts: no
  vars_files:
    - vars.yml
  roles:
    - name: wildfly_uninstall
  post_tasks:
    - name: "Flush handlers to ensure they are executed"
      ansible.builtin.meta: flush_handlers
