---
wildfly_uninstall_service_name: wildfly
wildfly_uninstall_home: /opt/wildfly/wildfly-34.0.0.Final
wildfly_uninstall_path_to_archive: /opt/wildfly/wildfly-34.0.0.Final.zip
wildfly_install_requires_become: false
