---
- name: "Verify that server was properly uninstalled."
  hosts: instance
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: "Display state of the WildFly service"
      ansible.builtin.debug:
        msg: "{{ ansible_facts.services.get('wildfly.service', 'Service not found') }}"

    - name: "Verify service is stopped and disabled (if still present in systemd)"
      ansible.builtin.assert:
        that:
          - ansible_facts.services[wildfly_uninstall_service_name + '.service'].status == 'disabled'
          - ansible_facts.services[wildfly_uninstall_service_name + '.service'].state == 'inactive'
        quiet: True
      when: (wildfly_uninstall_service_name + '.service') in ansible_facts.services

    - name: "Load metadata on server home: {{ wildfly_uninstall_home }}"
      become: "{{ wildfly_uninstall_require_privileges_escalation }}"
      ansible.builtin.stat:
        path: "{{ wildfly_uninstall_home }}"
      register: wfly_home

    - name: "Ensure server home does not exist"
      ansible.builtin.assert:
        that:
          - wfly_home is defined and wfly_home.stat is defined
          - wfly_home.stat.exists is defined and not wfly_home.stat.exists
        quiet: True

    - name: "Check systemd service file does not exist"
      become: "{{ wildfly_uninstall_require_privileges_escalation }}"
      ansible.builtin.stat:
        path: "/usr/lib/systemd/system/{{ wildfly_uninstall_service_name }}.service"
      register: systemd_service_file

    - name: "Check systemd conf file does not exist"
      become: "{{ wildfly_uninstall_require_privileges_escalation }}"
      ansible.builtin.stat:
        path: "/etc/{{ wildfly_uninstall_service_name }}.conf"
      register: systemd_conf_file

    - name: "Ensure systemd files are deleted (confirms handler executed)"
      ansible.builtin.assert:
        that:
          - systemd_service_file is defined and systemd_service_file.stat is defined
          - not systemd_service_file.stat.exists
          - systemd_conf_file is defined and systemd_conf_file.stat is defined
          - not systemd_conf_file.stat.exists
        fail_msg: "Systemd files still exist - handler may not have executed properly"
        quiet: True
