---
- name: Install wildfly
  hosts: all
  tasks:
    - name: "Include wildfly_systemd"
      ansible.builtin.include_role:
        name: middleware_automation.wildfly.wildfly_install

- name: Install multiple wildfly services
  hosts: all
  tasks:
    - name: "Include wildfly_systemd"
      ansible.builtin.include_role:
        name: middleware_automation.wildfly.wildfly_systemd
      vars:
        wildfly_node_id: "wildfly-{{ item }}"
        wildfly_instance_name: "wildfly-{{ item }}"
        wildfly_service_name: "wildfly-{{ item }}"
        wildfly_config_base: standalone-ha.xml
        wildfly_basedir_prefix: "/opt/instances/wildfly-{{ item }}/"
        wildfly_port_range_offset: "{{ 100 * (item) | int }}"
        wildfly_java_opts: '-Xmx512M -Xms512M'
      loop: "{{ range(0, 3) | list }}"
