---
- name: Install wildfly
  hosts: all
  tasks:
    - name: "Include wildfly_systemd"
      ansible.builtin.include_role:
        name: middleware_automation.wildfly.wildfly_install

- name: Install multiple wildfly services
  hosts: all
  tasks:
    - name: "Include wildfly_systemd"
      ansible.builtin.include_role:
        name: middleware_automation.wildfly.wildfly_systemd
      vars:
        wildfly_node_id: "wildfly-{{ item }}"
        wildfly_instance_name: "wildfly-{{ item }}"
        wildfly_service_name: "wildfly-{{ item }}"
        wildfly_config_base: standalone-ha.xml
        wildfly_basedir_prefix: "/opt/instances/wildfly-{{ item }}/"
        wildfly_port_range_offset: "{{ 100 * (item) | int }}"
        wildfly_java_opts: '-Xmx512M -Xms512M'
        wildfly_enable_yml_config: True
        wildfly_yml_configs:
          - yaml_configuration.yml.j2
      loop: "{{ range(0, 3) | list }}"

    - name: "Deploy webapp if test enabled"
      vars:
        path_to_app: /tmp/info.war
        download_app_url: 'https://drive.google.com/uc?export=download&id=13K7RCqccgH4zAU1RfOjYMehNaHB0A3Iq'
      when:
        - not eap_enable is defined or not eap_enable
      block:
        - name: "Deploy webapp"
          ansible.builtin.get_url:
            url: "{{ download_app_url }}"
            dest: "{{ path_to_app }}"

        - name: "Check that webapp is available"
          ansible.builtin.include_role:
            name: wildfly_utils
            tasks_from: jboss_cli.yml
          vars:
            jboss_home: "{{ wildfly_home }}"
            jboss_cli_query: "'deploy --force {{ path_to_app }}'"
