---
- name: Install wildfly
  hosts: all
  vars_files:
    - vars.yml
    - ../apps.yml
  tasks:
    - name: "Include wildfly_systemd"
      ansible.builtin.include_role:
        name: wildfly_install

- name: Install multiple wildfly services
  hosts: all
  vars_files:
    - vars.yml
  vars:
    wildfly_remote_destination_outbound_socket_binding:
        self:
          host: '127.0.0.1'
          port: 7600
        other:
          host: '127.0.0.1'
          port: 7700
  tasks:
    - name: "Include wildfly_systemd"
      ansible.builtin.include_role:
        name: wildfly_systemd
      vars:
        wildfly_node_id: "wildfly-{{ item }}"
        wildfly_instance_name: "wildfly-{{ item }}"
        wildfly_service_name: "wildfly-{{ item }}"
        wildfly_basedir_prefix: "{{ wildfly_instances_home }}/wildfly-{{ item }}/"
        wildfly_port_range_offset: "{{ 100 * (item) | int }}"
      loop: "{{ range(0, 3) | list }}"
