---
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      bin_ansible_callbacks: true
      callbacks_enabled: junit
    ssh_connection:
      pipelining: false
  playbooks:
    prepare: ../prepare.yml
    converge: converge.yml
    verify: verify.yml
  inventory:
    links:
      group_vars: ../group_vars
    group_vars:
      all:
        molecule_scenario_requires_app: true
  env:
    JUNIT_OUTPUT_DIR: "$PWD/junit"
    JUNIT_HIDE_TASK_ARGUMENTS: yes
    JUNIT_TASK_RELATIVE_PATH: "$PWD"
    JUNIT_TASK_CLASS: "true"
    JUNIT_REPLACE_OUT_OF_TREE_PATH: ""
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_COLLECTIONS_PATHS: "~/.ansible/collections/"
    ANSIBLE_ROLES_PATH: "../../roles"

verifier:
  name: ansible
  options:
    sudo: true

scenario:
  test_sequence:
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
