---
- name: Verify third server
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include wildfly_systemd"
      ansible.builtin.include_role:
        name: middleware_automation.wildfly.wildfly_validation
      vars:
        wildfly_node_id: "wildfly-{{ item }}"
        wildfly_instance_name: "wildfly-{{ item }}"
        wildfly_service_name: "wildfly-{{ item }}"
        wildfly_config_base: standalone-ha.xml
        wildfly_install_workdir: "/opt/wildfly/"
        wildfly_basedir_prefix: "/opt/instances/wildfly-{{ item }}/"
        wildfly_controller_port: "{{ 9990 + (100 * (item) | int) }}"
        wildfly_http_port: "{{ 8080 + (100 * (item) | int) }}"
        wildfly_validation_logfile_path_to_logfile: "{{ wildfly_basedir_prefix }}/standalone/log/server.log"
      loop: "{{ range(0, 3) | list }}"
