---
- name: Prepare
  hosts: all
  gather_facts: true
  vars_files:
    - apps.yml
  vars:
    sudo_pkg_name: 'sudo'
  tasks:

    - name: "Ensure {{ sudo_pkg_name }} is installed (if user is root)."
      ansible.builtin.yum:
        name: "{{ sudo_pkg_name }}"
      when:
        - ansible_user_id == 'root'

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: "Check if {{ sudo_pkg_name }} is installed."
      ansible.builtin.assert:
        that:
          - sudo_pkg_name in ansible_facts.packages

    - name: "Ensure required packages are installed."
      become: true
      ansible.builtin.yum:
        name:
          - java-11-openjdk
          - procps-ng
          - tzdata-java
        state: present

    - name: "Download apps if needed."
      when:
        - wildfly_apps is defined and wildfly_apps | length > 0
      block:

        - name: "Download apps if required"
          ansible.builtin.get_url:
            url: "{{ app.download_url }}"
            dest: "{{ app.path }}"
          loop: "{{ wildfly_apps }}"
          loop_control:
            loop_var: app

    - name: Display Ansible version
      ansible.builtin.debug:
        msg: "Ansible version is {{ ansible_version.full }}, running with Python {{ ansible_python_version }}."
