wildfly-configuration:
  system-property:
    JBOSS_ID:
      value: instance1
  subsystem:
    jgroups:
      stack:
        tcpping:
          transport:
            TCP:
              socket-binding: jgroups-tcp
          protocol:
            TCPPING:
              socket-bindings:
                - jgroups-instance
              properties:
                initial_hosts: "127.0.0.1[7600]"
                port_range: 0
            MERGE3:
            FD_SOCK:
            FD_ALL:
            VERIFY_SUSPECT:
            pbcast.NAKACK2:
            UNICAST3:
            pbcast.STABLE:
            pbcast.GMS:
            MFC:
            FRAG3:
      channel:
        ee:
          stack: tcpping
    transactions:
      node-identifier: instance1
    datasources:
      jdbc-driver:
        postgresql:
          driver-name: postgresql
          driver-xa-datasource-class-name: org.postgresql.xa.PGXADataSource
          driver-module-name: org.postgresql
      data-source:
          AddressBookDS:
            enabled: true
            jndi-name: java:jboss/datasources/AddressbookDS
            jta: true
            max-pool-size: 20
            min-pool-size: 2
            connection-url: "jdbc:postgresql://localhost/test"
            driver-name: postgresql
            user-name: addressbook
            password: addressbookpass
            validate-on-match: true
            background-validation: false
            background-validation-millis: 10000
            flush-strategy: FailingConnectionOnly
            transaction-isolation: TRANSACTION_READ_COMMITTED
    modcluster:
      proxy:
        default:
          proxies:
            - site1-loadbalancer
          advertise: false
          listener: ajp
    messaging-activemq:
      servers:
        default:
          jms-queues:
            ExpiryQueue:
              entries:
                - 'java:/jms/queue/ExpiryQueue'
            DLQ:
              entries:
                - 'java:/jms/queue/DLQ'
            CSIRequestQueue:
              entries:
                - 'java:/jms/queue/CSIRequestQueue'
            CsiDLQ:
              entries:
                - 'java:/jms/queue/CsiDLQ'
            CCDLQ:
              entries:
                - 'java:/jms/queue/CCDLQ'
            CCRequestQueue:
              entries:
                - 'java:/jms/queue/CCRequestQueue'
          address-settings:
            default:
              message-counter-history-day-limit: 10
              page-size-bytes: 2097152
              max-size-bytes: 10485760
              expiry-address: jms.queue.ExpiryQueue
              dead-letter-address: jms.queue.DLQ
              redistribution-delay: 1000
            CCRequestQueue:
              message-counter-history-day-limit: 10
              page-size-bytes: 2097152
              max-size-bytes: 10485760
              expiry-address: jms.queue.ExpiryQueue
              dead-letter-address: CCDLQ
              redistribution-delay: 1000
          security-settings:
            default:
              roles:
                guest:
                  send: true
                  delete-durable-queue: true
                  create-non-durable-queue: true
                  consume: true
          http-acceptors:
            http-acceptor-mq:
              http-listener: default
          http-connectors:
            http-connector-mq:
              socket-binding: http
              endpoint: http-acceptor
          cluster-password: ${jboss.messaging.cluster.password:CHANGEME}
          discovery-groups:
            activemq-discovery:
              jgroups-cluster: activemq-cluster
          broadcast-groups:
            activemq-broadcast:
              jgroups-cluster: activemq-cluster
              connectors:
                - 'http-connector'
          cluster-connections:
            activemq-cluster:
              cluster-connection-address: jms
              connector-name: http-connector
              discovery-group: activemq-discover
      remote-connector:
        messaging-remote-site1-amq1-connector:
          socket-binding: txn-recovery-environment
    ejb3:
      default-resource-adapter-name: RemoteConnectionFactory
    ee:
      service:
        default-bindings:
          jms-connection-factory: "java:jboss/RemoteConnectionFactory"
