---

- name: "Download file"
  ansible.builtin.get_url:
    url: "{{ file.url }}"
    dest: "{{ lookup('env', 'PWD') }}/{{ file.dest_filename }}"
    mode: "0664"
    validate_certs: "{{ eap_dot_validate_certs }}"
  delegate_to: localhost
  loop: "{{ eap_dot_download_files }}"
  loop_control:
    loop_var: file
  when:
    - eap_dot_download_files is defined
    - eap_dot_download_files | length > 0

- name: "Inform user if no file has been downloaded"
  ansible.builtin.debug:
    msg: "No file to download for this scenario."
  when:
    - not eap_dot_download_files is defined or eap_dot_download_files | length == 0
