---
- name: "Download driver directly to target: {{ wildfly_driver_config.module_name }}"
  ansible.builtin.uri:
    url: "{{ wildfly_driver_config.jar_url }}"
    dest: "{{ wildfly_driver_jar_installation_path }}"
    owner: "{{ wildfly_driver_user }}"
    group: "{{ wildfly_driver_group }}"
    mode: '0640'
    creates: "{{ wildfly_driver_jar_installation_path }}"
    selevel: s0
    serole: object_r
    setype: usr_t
    seuser: system_u
  when:
    - wildfly_driver_config.jar_url is defined
  become: "{{ wildfly_driver_become | default('yes') }}"
