---
wildfly_uninstall_require_privileges_escalation: "{{ wildfly_requires_become | default(true) }}"
wildfly_uninstall_service_name: "{{ wildfly_instance_name | default('wildfly') }}"
wildfly_uninstall_home: "{{ wildfly_install_workdir | default('/opt/wildfly/') }}wildfly-{{ wildfly_version | default('40.0.0.Final') }}/"
wildfly_uninstall_systemd_service_file: "/usr/lib/systemd/system/{{ wildfly_uninstall_service_name }}.service"
wildfly_uninstall_systemd_service_conf_file: "/etc/{{ wildfly_uninstall_service_name }}.conf"
wildfly_uninstall_delete_group: true
wildfly_uninstall_delete_groupname: "{{ wildfly_group | default('wildfly') }}"
wildfly_uninstall_delete_user: true
wildfly_uninstall_delete_username: "{{ wildfly_user | default('wildfly') }}"
