---
- name: "Ensure required parameters are provided."
  ansible.builtin.assert:
    that:
      - wildfly_firewalld_package_name is defined
    quiet: true

- name: "Ensure firewalld is available."
  become: "{{ wildfly_install_requires_become | default(true) }}"
  ansible.builtin.package:
    name: "{{ wildfly_firewalld_package_name }}"
    state: present
  when: ansible_distribution_major_version != '8'

- name: "Ensure firewalld is available on RHEL 8 (workaround for DNF module)"
  ansible.builtin.command:
    cmd: "dnf install -y {{ wildfly_firewalld_package_name }}"
  become: "{{ wildfly_install_requires_become | default(true) }}"
  register: wildfly_firewalld_dnf_install_result
  changed_when:
    - "'Installing:' in wildfly_firewalld_dnf_install_result.stdout or 'Upgrading:' in wildfly_firewalld_dnf_install_result.stdout"
  when: ansible_distribution_major_version == '8'

- name: "Ensure firewalld is running."
  become: "{{ wildfly_install_requires_become | default(true) }}"
  ansible.builtin.service:
    name: "{{ wildfly_firewalld_service_name | default('firewalld') }}"
    state: started
    enabled: true
