---
wildfly_version: '39.0.0.Final'
wildfly_config_custom_file: "files/wildfly-{{ (wildfly_version.split('.'))[0:2] | join('.') }}-custom.xml"
wildfly_enable_yml_config: true
wildfly_yml_configs:
  - yaml_configuration.yml.j2
