---
# Download WildFly zip to controller for offline install (no Prospero path)
- name: Prepare offline archive
  hosts: all
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: "Download zipfile from {{ wildfly_install_download_url }} into {{ wildfly_install_download_controller_download_dir }}"
      delegate_to: localhost
      run_once: true
      ansible.builtin.get_url:
        url: "{{ wildfly_install_download_url }}"
        dest: "{{ wildfly_install_download_controller_download_dir }}"
        mode: '0644'
      when:
        - not eap_version is defined

- import_playbook: ../prepare.yml
