---
- name: Converge
  hosts: all
  vars:
    wildfly_install_user: 'wildfly'
    wildfly_install_group: "{{ wildfly_install_user }}"
    wildfly_install_use_prospero: True
  collections:
    - middleware_automation.wildfly
  tasks:
    - name: "Run Prospero scenario only upstream."
      block:
        - name: "Ensure required local user and group exists."
          ansible.builtin.include_role:
            name: wildfly_install
            tasks_from: user.yml

        - name: "Install server using Prospero"
          ansible.builtin.include_role:
            name: wildfly_install

        - name: "Run server with systemd"
          ansible.builtin.include_role:
            name: wildfly_systemd
      when:
        - eap_enable is not defined or not eap_enable
        - prospero_scenario_enable is defined and prospero_scenario_enable
