---
- name: Converge
  hosts: all
  vars_files:
    - ../apps.yml
  vars:
    wildfly_install_user: 'wildfly'
    wildfly_install_group: "{{ wildfly_install_user }}"
    wildfly_install_use_prospero: true
    wildfly_prospero_scenario_enable: true
  tasks:
    - name: "Run Prospero scenario only upstream."
      when:
        - wildfly_prospero_scenario_enable is defined and wildfly_prospero_scenario_enable
        - not eap_enable is defined or not eap_enable
      block:
        - name: "Install server using Prospero"
          ansible.builtin.include_role:
            name: middleware_automation.wildfly.wildfly_install

        - name: "Run server with systemd"
          ansible.builtin.include_role:
            name: middleware_automation.wildfly.wildfly_systemd
