---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/requirements.yml
driver:
  name: docker
lint: |
  ansible-lint --version
  ansible-lint -v
platforms:
  - name: instance
    image: registry.access.redhat.com/ubi8/ubi-init:latest
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    port_bindings:
      - 8080:8080
    published_ports:
      - 0.0.0.0:8080:8080/TCP
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
    verify: verify.yml
  inventory:
    host_vars:
      instance:
        wildfly_java_package_name: java-11-openjdk-headless
      localhost:
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_COLLECTIONS_PATHS: "~/.ansible/collections/"
    ANSIBLE_ROLES_PATH: "../../roles"
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - lint
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
