---
- name: Prepare
  hosts: all
  tasks:

    - name: "Ensure required packages are installed."
      ansible.builtin.yum:
        name:
          - sudo
          - java-11-openjdk-headless
          - procps-ng
        state: present
      when:
        - not eap_enable is defined or not eap_enable
        - prospero_scenario_enable is defined and prospero_scenario_enable
