---
- name: "Check that required parameters are provided"
  ansible.builtin.assert:
    that:
      - eap_subs_group_install_name is defined
      - eap_version is defined
    quiet: true
    fail_msg: "Missing required parameters"

- name: "Uninstall group package"
  when:
    - wildfly_subs is defined
    - wildfly_subs_config.skip_group_remove is defined
    - not wildfly_subs_config.skip_group_remove
  block:

    - name: "Ensure EAP group package is removed: {{ eap_subs_group_install_name }}"
      ansible.builtin.command: "dnf group remove -y {{ eap_subs_group_install_name }}"
      register: wildfly_subs_dnf_group_res
      changed_when:
        - 'not "Nothing to do." in wildfly_subs_dnf_group_res.stdout'

    - name: "Ensure JBoss EAP Home has been removed"
      ansible.builtin.file:
        path: "{{ wildfly_subs_rpm_install_root_dir }}"
        state: absent
      when:
        - wildfly_subs_config.remove_root_dir is defined
        - wildfly_subs_config.remove_root_dir

- name: "Disable repository"
  when:
    - wildfly_subs is defined
    - wildfly_subs_config.check_repo_disabled is defined
    - wildfly_subs_config.check_repo_disabled
  block:
    - name: "Check that required parameters are provided"
      ansible.builtin.assert:
        that:
          - ansible_facts['distribution_major_version'] is defined
          - ansible_facts['architecture'] is defined
        quiet: true
        fail_msg: "Missing required parameters"
      when:
        - not eap_repos_name is defined

    - name: "Determine EAP repo name."
      ansible.builtin.set_fact:
        wildfly_subs_eap_repos_name: >-
          jb-eap-{{ eap_version }}-for-rhel-{{
          ansible_facts['distribution_major_version'] }}-{{
          ansible_facts['architecture'] }}-rpms
      when:
        - not eap_repos_name is defined

    - name: "Ensure JBoss EAP repos are disabled: {{ eap_version }}"
      ansible.builtin.command: "subscription-manager repos --disable={{ eap_repos_name }}"
      changed_when: false
