---
- name: Deploy first wildfly
  import_playbook: ../../playbooks/playbook.yml
  vars:
    id: 1
    wildfly_node_id: "wildfly-{{ id }}"
    wildfly_instance_name: "wildfly-{{ id }}"
    wildfly_service_name: "wildfly-{{ id }}"
    wildfly_config_base: standalone-ha.xml
    wildfly_install_workdir: "/opt/wildfly-{{ id }}/"
    wildfly_port_range_offset: "{{ 100 * (id - 1) | int }}"
    jdbc_drivers: []

- name: Deploy second wildfly
  import_playbook: ../../playbooks/playbook.yml
  vars:
    id: 2
    wildfly_node_id: "wildfly-{{ id }}"
    wildfly_instance_name: "wildfly-{{ id }}"
    wildfly_service_name: "wildfly-{{ id }}"
    wildfly_config_base: standalone-ha.xml
    wildfly_install_workdir: "/opt/wildfly-{{ id }}/"
    wildfly_port_range_offset: "{{ 100 * (id - 1) | int }}"
    jboss_cli_controller_port: 10090
    jdbc_drivers: []

- name: Deploy third wildfly
  import_playbook: ../../playbooks/playbook.yml
  vars:
    id: 3
    wildfly_node_id: "wildfly-{{ id }}"
    wildfly_instance_name: "wildfly-{{ id }}"
    wildfly_service_name: "wildfly-{{ id }}"
    wildfly_config_base: standalone-ha.xml
    wildfly_install_workdir: "/opt/wildfly-{{ id }}/"
    wildfly_port_range_offset: "{{ 100 * (id - 1) | int }}"
    jboss_cli_controller_port: 10190
    jdbc_drivers: []
