---
- name: Converge
  hosts: all
  collections:
    - middleware_automation.wildfly
  vars_files:
    - vars.yml
  tasks:
    - name: Include wildfly_install role
      ansible.builtin.include_role:
        name: wildfly_install

    - name: Include wildfly_systemd role
      ansible.builtin.include_role:
        name: wildfly_systemd

    - name: Include wildfly_driver role
      ansible.builtin.include_role:
        name: wildfly_driver
      vars:
        jdbc_driver_module_dir: "{{ wildfly_home }}/modules/org/postgresql/main"
        jdbc_driver_version: 9.2-1002-jdbc4
        jdbc_driver_jar_filename: "postgresql-{{ jdbc_driver_version }}.jar"
        jdbc_driver_jar_url: "https://repo.maven.apache.org/maven2/org/postgresql/postgresql/{{ jdbc_driver_version }}/{{ jdbc_driver_jar_filename }}"
        jdbc_driver_jar_installation_path: "{{ jdbc_driver_module_dir }}/{{ jdbc_driver_jar_filename }}"
        jdbc_driver_module_name: "org.postgresql"

    - name: Include jboss_eap role
      ansible.builtin.include_role:
        name: jboss_eap
