---
driver:
  name: ${CI_DRIVER:-docker}
platforms:
  - name: instance
    image: registry.access.redhat.com/ubi8/ubi-init:latest
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    port_bindings:
      - 8080:8080
    published_ports:
      - 0.0.0.0:8080:8080/TCP
    packages:
      - sudo
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      bin_ansible_callbacks: true
      callbacks_enabled: junit
    ssh_connection:
      pipelining: false
  playbooks:
    prepare: ../prepare.yml
    converge: converge.yml
    verify: verify.yml
  inventory:
    links:
      group_vars: ../group_vars
    host_vars:
      instance:
        wildfly_java_package_name: java-11-openjdk-headless
      localhost:
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
  env:
    JUNIT_OUTPUT_DIR: "$PWD/junit"
    JUNIT_HIDE_TASK_ARGUMENTS: yes
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_COLLECTIONS_PATHS: "~/.ansible/collections/"
    ANSIBLE_ROLES_PATH: "../../roles"
verifier:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
