---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - vars.yml
  collections:
    - middleware_automation.wildfly
  tasks:
    - name: "Run validation provided by collection"
      include_role:
        name: middleware_automation.wildfly.wildfly_validation
      vars:
        wildfly_service_name: wildfly
