---
- ansible.builtin.assert:
    that:
      - validation_query is defined
      - expected_result is defined
      - wildfly_home is defined
    quiet: true
    fail_msg: "Missing required parameters"

- name: "Use CLI query to validate service state: {{ validation_query }}"
  ansible.builtin.include_role:
    name: jboss_eap
    tasks_from: jboss_cli.yml
  vars:
    query: "'{{ validation_query }}'"
    jboss_home: "{{ wildfly_home }}"
  loop:
    - '/core-service=server-environment:read-attribute(name=start-gracefully)'
    - '/subsystem=undertow/server=default-server/http-listener=default:read-attribute(name=enabled)'

- ansible.builtin.assert:
    that:
      - cli_result is defined
      - cli_result.rc is defined
      - cli_result.rc == 0
    quiet: true
    fail_msg: "FAIL"
