---
- name: "Check arguments"
  ansible.builtin.assert:
    that:
      - wildfly_snapshot_jboss_home is defined
      - wildfly_snapshot_jboss_cli_controller_host is defined
      - wildfly_snapshot_jboss_cli_controller_port is defined
    fail_msg: "Missing required parameters for wildfly_snapshot role."
    quiet: true

- name: "Take configuration snapshot"
  ansible.builtin.include_tasks: take_snapshot.yml
