---
- name: "Escalate privilege if required."
  become: "{{ wildfly_install_require_privileges_escalation }}"
  block:
    - name: "Check if work directory exists: {{ wildfly_install_config.workdir }}"
      ansible.builtin.stat:
        path: "{{ wildfly_install_config.workdir }}"
      register: wildfly_install_work_dir_stat

    - name: "Check if work directory is readable: {{ wildfly_install_config.workdir }}"
      ansible.builtin.assert:
        that:
          - wildfly_install_work_dir_stat.stat.exists
          - wildfly_install_work_dir_stat.stat.readable
        fail_msg: "Archive directory {{ wildfly_install_config.workdir }} either does not exist or is not readable"
        success_msg: "Archive directory {{ wildfly_install_config.workdir }} is readable"
      when: wildfly_install_work_dir_stat.stat.exists

    - name: "Create work directory if not exists: {{ wildfly_install_config.workdir }}"
      ansible.builtin.file:
        path: "{{ wildfly_install_config.workdir }}"
        state: directory
        owner: "{{ wildfly_install_config.user }}"
        group: "{{ wildfly_install_config.group }}"
        mode: '0750'
        selevel: s0
        serole: object_r
        setype: usr_t
        seuser: system_u
        recurse: false
      when: not wildfly_install_work_dir_stat.stat.exists

    - name: "Check if archive directory exists: {{ wildfly_install_config.archive_dir }}"
      ansible.builtin.stat:
        path: "{{ wildfly_install_config.archive_dir }}"
      register: wildfly_install_archive_dir_stat

    - name: "Check if archive directory is readable: {{ wildfly_install_config.archive_dir }}"
      ansible.builtin.assert:
        that:
          - wildfly_install_archive_dir_stat.stat.exists
          - wildfly_install_archive_dir_stat.stat.readable
        fail_msg: "Archive directory {{ wildfly_install_config.archive_dir }} either does not exist or is not readable"
        success_msg: "Archive directory {{ wildfly_install_config.archive_dir }} is readable"
      when: wildfly_install_archive_dir_stat.stat.exists

    - name: "Create archive directory if not exists: {{ wildfly_install_config.archive_dir }}"
      ansible.builtin.file:
        path: "{{ wildfly_install_config.archive_dir }}"
        state: directory
        owner: "{{ wildfly_install_config.user }}"
        group: "{{ wildfly_install_config.group }}"
        mode: '0750'
        selevel: s0
        serole: object_r
        setype: usr_t
        seuser: system_u
        recurse: false
      when: not wildfly_install_archive_dir_stat.stat.exists
