---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - wildfly_install_config.user is defined
    quiet: true

- name: Set wildfly group
  ansible.builtin.set_fact:
    wildfly_install_group_name: "{{ wildfly_install_config.group | default(wildfly_install_config.user) }}"

- name: "Ensure group {{ wildfly_install_group_name }} exists."
  become: "{{ wildfly_install_requires_become | default(true) }}"
  ansible.builtin.group:
    name: "{{ wildfly_install_group_name }}"

- name: "Ensure user {{ wildfly_install_config.user }} exists."
  become: "{{ wildfly_install_requires_become | default(true) }}"
  ansible.builtin.user:
    name: "{{ wildfly_install_config.user }}"
    group: "{{ wildfly_install_group_name }}"
    state: present
    system: True
