---
- import_playbook: ../../playbooks/validate.yml
  vars:
    wildfly_install_workdir: /apps/
    wildfly_user: mware
    wildfly_group: sysgroup
    wildfly_java_package_name: java-17-openjdk-headless
    wildfly_validation_skip_jdbc_drivers_check: false

- name: Validation
  hosts: all
  tasks:
    - name: Verify we are running on requested jvm
      ansible.builtin.shell: |
        ps -ef | grep /etc/alternatives/jre_11/bin/java | grep -v grep
      changed_when: False
