---
- name: 'Restart Wildfly'
  ansible.builtin.include_tasks: service.yml
  vars:
    instance_state: restarted
  listen: "restart_wildfly"

- name: "Perform daemon-reload"
  ansible.builtin.systemd:
    daemon_reload: yes
