---
- name: 'Restart Wildfly'
  ansible.builtin.include_tasks: service.yml
  vars:
    instance_state: restarted
  listen: "restart_wildfly"

- name: "Perform daemon-reload"
  become: "{{ wildfly_install_requires_become | default(true) }}"
  ansible.builtin.systemd:
    daemon_reload: true

- name: Execute restorecon
  become: "{{ wildfly_install_requires_become | default(true) }}"
  ansible.builtin.command: "restorecon -R -v {{ wildfly_install_workdir }}"
  register: selinux_output
  changed_when: selinux_output.stdout_lines | length > 0
  when: wildfly_selinux_enabled
  listen: exec_restorecon
