argument_specs:
    main:
        options:
            # line 2 of defaults/main.yml
            wildfly_prospero_version:
                default: "1.2.0.Final"
                description: "Version of Prospero to use"
                type: "str"

            # line 3 of defaults/main.yml
            wildfly_prospero_name:
                default: "prospero"
                description: "Constant for the name of the prospero tool"
                type: "str"

            # line 4 of defaults/main.yml
            wildfly_prospero_install_dir:
                default: "/opt/prospero"
                description: "Path to the installation dir for Prospero"
                type: "str"

            # line 5 of defaults/main.yml
            wildfly_prospero_profile_name:
                default: "wildfly"
                description: "Name of the Wildfly profile for the server to install"
                type: "str"

            # line 6 of defaults/main.yml
            wildfly_prospero_scenario_enable:
                default: true
                description: "Specificy to Molecule if it should run the Prospero scenario"
                type: "bool"

            # line 7 of defaults/main.yml
            wildfly_prospero_archive_name:
                default: "{{ wildfly_prospero_name }}-{{ wildfly_prospero_version }}.zip"
                description: "Name of the Prospero archive"
                type: "str"

            # line 8 of defaults/main.yml
            wildfly_prospero_home:
                default: "{{ wildfly_prospero_install_dir }}/{{ wildfly_prospero_name }}-{{ wildfly_prospero_version }}"
                description: "Home of the prospero tool"
                type: "str"

            # line 9 of defaults/main.yml
            wildfly_install_manifest_dir:
                default: "{{ wildfly_install_workdir }}/manifest"
                description: "Path on target to the Prospero manifest"
                type: "str"

            # line 10 of defaults/main.yml
            wildfly_prospero_download_url:
                default: "https://github.com/wildfly-extras/prospero/releases/download/{{ wildfly_prospero_version }}/prospero-{{ wildfly_prospero_version }}.zip"
                description: "URL to download Prospero"
                type: "str"

            # line 11 of defaults/main.yml
            wildfly_prospero_download_check_ssl:
                default: false
                description: "Should Ansible check SSL when downloading Prospero"
                type: "bool"
    downstream:
        options:
            eap_prospero_version:
                default: "1.1.6.Final-redhat-00001"
                description: "Version of Prospero to use"
                type: "str"
