---
allow_duplicates: true
galaxy_info:
  role_name: wildfly_prospero
  namespace: middleware_automation
  author: Romain Pelisse, Andrew Block, Harsha Cherukuri, Guido Grazioli
  description: Integrate Prospero as an alternative installation mecanism for Wildfly
  company: Red Hat, Inc.

  license: Apache License 2.0

  min_ansible_version: "2.9"

  platforms:
   - name: EL
     versions:
     - 8

  galaxy_tags:
    - java
    - jboss
    - wildfly
    - cli
    - server
    - jdbc
