---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - wildfly_systemd_config is defined
      - wildfly_systemd_config.home is defined
      - wildfly_systemd_config.user is defined
      - wildfly_systemd_config.group is defined
    quiet: true

- name: "Validate node identifier length"
  ansible.builtin.assert:
    that:
      - wildfly_systemd_node_id | length <= 23
    quiet: true
    fail_msg: "The node ID in variable wildfly_systemd_node_id cannot exceed 23 characters length"

- name: "Ensure that version is correct for yaml config extension"
  ansible.builtin.include_tasks: yml_config_version_prereq.yml
  when: wildfly_systemd_enable_yml_config

- name: "Ensure required local user and group exists."
  ansible.builtin.include_role:
    name: wildfly_install
    tasks_from: user.yml
  vars:
    wildfly_install_user: "{{ wildfly_systemd_user }}"
    wildfly_install_group: "{{ wildfly_systemd_group }}"

- name: 'Check if PID directory exists'
  become: "{{ wildfly_systemd_require_privilege_escalation | default(true) }}"
  ansible.builtin.stat:
    path: "{{ wildfly_systemd_config.selinux.pid_path }}"
  register: wildfly_systemd_pid_directory

- name: 'Create PID directory path if not exists'
  become: "{{ wildfly_systemd_require_privilege_escalation | default(true) }}"
  ansible.builtin.file:
    path: "{{ wildfly_systemd_config.selinux.pid_path }}"
    state: directory
    mode: '0755'
    owner: "{{ wildfly_systemd_config.user }}"
    group: "{{ wildfly_systemd_config.group }}"
    selevel: s0
    serole: object_r
    setype: var_run_t
    seuser: system_u
  when: not wildfly_systemd_pid_directory.stat.exists
  notify: exec_restorecon

- name: "Ensure server configuration and systemd configuration are set"
  ansible.builtin.include_tasks: systemd.yml
  vars:
    basedir: "{{ wildfly_systemd_basedir_prefix | default(wildfly_systemd_config.home) }}/standalone"

- name: "Ensure server's apps are deployed"
  ansible.builtin.include_tasks: apps.yml
  vars:
    wildfly_basedir: "{{ wildfly_systemd_basedir_prefix | default(wildfly_systemd_config.home) }}/standalone"
  when:
    - wildfly_apps is defined and wildfly_apps | length > 0
