---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - instance_name is defined
      - instance_state is defined
    quiet: true

- name: "Start Wildfly instance {{ instance_name }}"
  ansible.builtin.service:
    name: "{{ instance_name }}"
    state: "{{ instance_state }}"
    enabled: "{{ wildfly_systemd.enabled | default(omit) }}"
