---
- name: Check if YAML configuration extension is supported in WildFly
  ansible.builtin.assert:
    that:
      - (wildfly_systemd_version.split('.')[:3] | join('.') is version('26.0.1', '>='))
    fail_msg: "YAML configuration extension is not supported in this WildFly version."
  when:
    - eap_systemd_enable is not defined or (not eap_systemd_enable | bool)

- name: "Check latest applied patch checksum file"
  become: "{{ wildfly_systemd_require_privilege_escalation | default(true) }}"
  ansible.builtin.stat:
    path: "{{ wildfly_systemd_home }}/.latest_applied_patch.txt"
  register: wildfly_systemd_latest_patch_file_stat

- name: "Execute only on eap 7.x and higher version and if eap_systemd_enable is true."
  when:
    - eap_systemd_enable is defined and (eap_systemd_enable | bool)
    - eap_systemd_version.split('.')[:1] | join('.') is version('7', '>=')
  block:
    - name: Check latest patch checksum file exists
      ansible.builtin.assert:
        that:
          - wildfly_systemd_latest_patch_file_stat is defined
          - wildfly_systemd_latest_patch_file_stat.stat is defined
          - wildfly_systemd_latest_patch_file_stat.stat.exists
        quiet: true
        fail_msg: "Can only enable YAML configuration with EAP >= 7.4.7 (found: EAP 7.4.0)"
      when:
        - eap_systemd_version.split('.')[:1] | join('.') is version('7', '==')

    - name: Check current EAP patch installed
      ansible.builtin.slurp:
        src: "{{ wildfly_systemd_home }}/.latest_applied_patch.txt"
      register: wildfly_systemd_slurped_eap_systemd_version
      become: "{{ wildfly_systemd_require_privilege_escalation | default(true) }}"
      when:
        - eap_systemd_apply_cp is defined and (eap_systemd_apply_cp | bool)
        - wildfly_systemd_latest_patch_file_stat.stat.exists

    - name: Check arguments for yaml configuration
      ansible.builtin.assert:
        that:
          - >-
            (eap_systemd_version.split('.')[:1] | join('.') is version('8', '>=')) or
            (wildfly_systemd_slurped_eap_systemd_version is defined and
            wildfly_systemd_slurped_eap_systemd_version.content | b64decode is version('7.4.7', '>='))
        quiet: true
        fail_msg: "Can only enable YAML configuration with EAP >= 7.4.7 or EAP 8+"

- name: Check if YAML configuration extension is supported in EAP
  ansible.builtin.assert:
    that:
      - >-
        (eap_systemd_version.split('.')[:1] | join('.') is version('8', '>=')) or
        (wildfly_systemd_slurped_eap_systemd_version is defined and
        wildfly_systemd_slurped_eap_systemd_version.content | b64decode is version('7.4.7', '>='))
    fail_msg: "YAML configuration extension is not supported in this EAP version"
  when:
    - eap_systemd_enable is defined and (eap_systemd_enable | bool)
