---
- name: Converge
  hosts: all
  vars_files:
    - vars.yml
    - ../apps.yml
    - ../vars.yml
  collections:
    - middleware_automation.wildfly
  roles:
    - role: wildfly_install
    - role: wildfly_systemd
