---
- name: Verify
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: "Include apps verification"
      ansible.builtin.include_tasks: ../verify_apps.yml
      when:
        - wildfly_apps is defined and wildfly_apps | length > 0

    - name: "Verify the property using wildfly_validation_queries (The Validation)"
      ansible.builtin.include_role:
        name: middleware_automation.wildfly.wildfly_validation
      vars:
        wildfly_validation_queries:
          - query: '/system-property=testyml:read-attribute(name=value)'
            expected_result: 'valueyml'
            expected_result_undefined: false
          - query: '/system-property=test:read-attribute(name=value)'
            expected_result: 'testvalue'
            expected_result_undefined: false
