---
# internal variables
wildfly_install:
  download_url: "{{ wildfly_install_download_url }}"
  workdir: "{{ wildfly_install_workdir }}"
  archive_dir: "{{ wildfly_archive_dir }}"
  archive_name: "{{ wildfly_archive_filename if wildfly_enable else wildfly_archive_filename }}"
  home: "{{ wildfly_home if wildfly_enable else wildfly_home }}"
  config: "{{ wildfly_config_base }}"
  user: "{{ wildfly_user }}"
  group: "{{ wildfly_group }}"
  java:
    package_name: "{{ wildfly_java_package_name }}"

wildfly_install_rhn:
  id: "{{ rhn_ids[wildfly_version].id }}"
  cp_id: "{{ rhn_ids[wildfly_version].cp.id }}"
  cp_v: "{{ rhn_ids[wildfly_version].cp.v }}"

rhn_ids:
  '7.4.0':  # noqa vars_in_vars_files_have_valid_names
    id: '99481'
    cp:
      id: '99481'
      v: '7.4.5'
