---
- name: Import shared molecule prepare playbook
  ansible.builtin.import_playbook: ../prepare.yml

- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: "Ensure required packages are installed using wildfly_java_version variable (RHEL 9+)"
      become: "{{ wildfly_requires_become | default(true) }}"
      ansible.builtin.dnf:
        name:
          - >-
            {{ 'java-1.8.0-openjdk' if (wildfly_java_version | string == '1.8')
            else ('java-' + (wildfly_java_version | string) + '-openjdk-headless') }}
          - procps-ng
          - tzdata-java
        state: present
      when: ansible_facts.distribution_major_version != '8'

    - name: "Ensure required packages are installed using wildfly_java_version variable (RHEL 8)"
      become: "{{ wildfly_requires_become | default(true) }}"
      ansible.builtin.command:
        cmd: >-
          dnf install -y {{ 'java-1.8.0-openjdk' if (wildfly_java_version | string == '1.8')
          else ('java-' + (wildfly_java_version | string) + '-openjdk-headless') }}
          procps-ng tzdata-java
      changed_when: false
      when: ansible_facts.distribution_major_version == '8'

    - name: "Install and start WildFly"
      ansible.builtin.include_role:
        name: wildfly_install

    - name: "Setup WildFly as systemd service"
      ansible.builtin.include_role:
        name: wildfly_systemd
      vars:
        wildfly_systemd_java_package_name: >-
          {{ 'java-1.8.0-openjdk' if (wildfly_java_version | string == '1.8')
          else ('java-' + (wildfly_java_version | string) + '-openjdk-headless') }}

    - name: "Wait for WildFly to be ready"
      ansible.builtin.wait_for:
        host: "localhost"
        port: "9990"
        delay: 10
        timeout: 120

    - name: Display Ansible version
      ansible.builtin.debug:
        msg: "Ansible version is {{ ansible_version.full }}, running with Python {{ ansible_facts['python_version'] }}."
