---
- import_playbook: ../prepare.yml

- name: Prepare
  hosts: all
  gather_facts: true
  vars_files:
    - ../group_vars/all/vars.yml
  tasks:
    - name: "Set wildfly_java_version default based on RHEL version if not defined"
      ansible.builtin.set_fact:
        wildfly_java_version: "{{ wildfly_java_version | default(21 if ansible_facts.distribution_major_version == '10' else 17) }}"
      when: wildfly_java_version is not defined

    - name: "Ensure required packages are installed using wildfly_java_version variable (RHEL 9+)"
      become: "{{ wildfly_install_requires_become | default(true) }}"
      ansible.builtin.yum:
        name:
          - "{{ 'java-1.8.0-openjdk' if wildfly_java_version|default(21 if ansible_facts.distribution_major_version == '10' else 17)|string == '1.8' else 'java-' + wildfly_java_version|default(21 if ansible_facts.distribution_major_version == '10' else 17)|string + '-openjdk-headless' }}"
          - procps-ng
          - tzdata-java
        state: present
      when: ansible_facts.distribution_major_version != '8'

    - name: "Ensure required packages are installed using wildfly_java_version variable (RHEL 8)"
      become: "{{ wildfly_install_requires_become | default(true) }}"
      ansible.builtin.command:
        cmd: "dnf install -y {{ 'java-1.8.0-openjdk' if wildfly_java_version|default(17)|string == '1.8' else 'java-' + wildfly_java_version|default(17)|string + '-openjdk-headless' }} procps-ng tzdata-java"
      changed_when: false
      when: ansible_facts.distribution_major_version == '8'

    - name: "Install and start WildFly"
      ansible.builtin.include_role:
        name: wildfly_install

    - name: "Setup WildFly as systemd service"
      ansible.builtin.include_role:
        name: wildfly_systemd
      vars:
        wildfly_java_package_name: "{{ 'java-1.8.0-openjdk' if wildfly_java_version|default(21 if ansible_facts.distribution_major_version == '10' else 17)|string == '1.8' else 'java-' + wildfly_java_version|default(21 if ansible_facts.distribution_major_version == '10' else 17)|string + '-openjdk-headless' }}"

    - name: "Wait for WildFly to be ready"
      ansible.builtin.wait_for:
        host: "{{ jboss_cli_controller_host | default('localhost') }}"
        port: "{{ jboss_cli_controller_port | default('9990') }}"
        delay: 10
        timeout: 120

    - name: Display Ansible version
      ansible.builtin.debug:
        msg: "Ansible version is {{ ansible_version.full }}, running with Python {{ ansible_python_version }}."
