---
galaxy_info:
  role_name: wildfly_uninstall
  namespace: middleware_automation
  author: Romain Pelisse, Andrew Block, Harsha Cherukuri, Guido Grazioli
  description: Uninstalls wildfly or EAP from ansible nodes that were provisioned by role wildfly_install
  company: Red Hat, Inc.

  license: Apache License 2.0

  min_ansible_version: "2.9"

  platforms:
   - name: EL
     versions:
     - 8

  galaxy_tags:
    - java
    - jboss
    - wildfly
    - cli
    - server
    - systemd
