---
- import_playbook: ../../playbooks/playbook.yml
  vars:
    wildfly_custom_proxy_port: 6666
    wildfly_enable_yml_config: True
    wildfly_config_base: 'standalone-full-ha.xml'
    wildfly_yml_configs_repository: ../molecule/yaml_config_validation/templates/
    wildfly_yml_configs:
        - yaml_configuration.yml.j2
        - yaml_socket_bindings.yml.j2
    eap_offline_install: True
    eap_apply_cp: True
    eap_patch_version: 7.4.9
