---
- import_playbook: ../../playbooks/playbook.yml
  vars:
    wildfly_apps:
      - { path: /tmp/kitchensink.war, download_url: 'https://github.com/rpelisse/wildfly-quickstarts/releases/download/kitchensink_wildfly31_1.0/kitchensink.war', root: '/kitschensink' }
      #  - { path: /tmp/info.war, download_url: 'https://drive.google.com/uc?export=download&id=13K7RCqccgH4zAU1RfOjYMehNaHB0A3Iq', root: '/info' }
    wildfly_custom_proxy_port: 6666
    wildfly_enable_yml_config: true
    wildfly_config_base: 'standalone-full-ha.xml'
    wildfly_yml_configs_repository: ../molecule/yaml_config_validation/templates/
    wildfly_yml_configs:
        - yaml_configuration.yml.j2
        - yaml_socket_bindings.yml.j2
        - yaml_infinispan.yml.j2
