---
- name: Prepare
  hosts: all
  vars_files:
    - vars.yml
  pre_tasks:
    - name: "Ensure required packages are installed."
      ansible.builtin.yum:
        name:
          - sudo
          - java-11-openjdk
          - tzdata-java
          - procps-ng
        state: present

    - name: Display Ansible version
      ansible.builtin.debug:
        msg: "Ansible version is  {{ ansible_version.full }}"
