---
wildfly_config_base: standalone-full-ha.xml
wildfly_instances_home: '/opt/instances/'
wildfly_systemd_java_opts: '-Xmx512M -Xms512M'
wildfly_systemd_enable_yml_config: true
wildfly_systemd_yml_configs:
  - yaml_configuration.yml.j2
  - configure_tcp_ping.yml.j2
