---
wildfly_config_base: standalone-full-ha.xml
wildfly_instances_home: '/opt/instances/'
wildfly_java_opts: '-Xmx512M -Xms512M'
wildfly_enable_yml_config: True
wildfly_yml_configs:
  - yaml_configuration.yml.j2
  - configure_tcp_ping.yml.j2
wildfly_apps:
  - { path: /tmp/kitchensink.war, download_url: 'https://github.com/rpelisse/wildfly-quickstarts/releases/download/kitchensink_wildfly31_1.0/kitchensink.war', root: '/kitschensink' }
  #  - { path: /tmp/info.war, download_url: 'https://drive.google.com/uc?export=download&id=13K7RCqccgH4zAU1RfOjYMehNaHB0A3Iq', root: '/info' }
#  - { path: /tmp/kitchensink.war, download_url: 'https://github.com/rpelisse/wildfly-quickstarts/releases/download/kitchensink_wildfly31_1.0/kitchensink.war', root: '/kitschensink' }
