---
wildfly_install_version: '40.0.0.Final'
wildfly_install_archive_filename: "wildfly-{{ wildfly_install_version }}.zip"
wildfly_install_archive_filename_on_controller: true
wildfly_install_download_baseurl: 'https://github.com/wildfly/wildfly/releases/download'
wildfly_install_workdir: '/opt/wildfly/'
wildfly_install_require_privileges_escalation: true
wildfly_install_home: "{{ wildfly_install_workdir }}wildfly-{{ wildfly_install_version }}/"
wildfly_install_download_url: "{{ wildfly_install_download_baseurl }}/{{ wildfly_install_version }}/{{ wildfly_install_archive_filename }}"
wildfly_install_archive_dir: "{{ wildfly_install_workdir }}"
wildfly_install_config_base: 'standalone.xml'
wildfly_install_config_custom_file: ''
wildfly_install_user: 'wildfly'
wildfly_install_group: "{{ wildfly_install_user }}"
wildfly_install_java_version: 21
wildfly_install_java_package_name: "{{ 'java-1.8.0-openjdk' if wildfly_install_java_version | string == '1.8' else 'java-' + wildfly_install_java_version | string + '-openjdk-headless' }}"
wildfly_install_force_reinstall_config_base: false

wildfly_install_offline_install: false
wildfly_install_prereqs_packages:
  - unzip
  - tar
  - iproute
  - sed
  - sudo
  - tzdata-java

wildfly_install_node_id: "{{ inventory_hostname_short }}"
wildfly_install_instance_name: 'wildfly'
wildfly_install_selinux_enabled: false
wildfly_install_cluster_enabled: false
