---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    wildfly_home: '/opt/wildfly/wildfly-26.0.0.Final'
  collections:
    - middleware_automation.wildfly
  roles:
    - wildfly_validation
