---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  galaxy-importer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core galaxy-importer

      - name: Build collection
        run: ansible-galaxy collection build .

      - name: Run galaxy-importer
        run: python -m galaxy_importer.main middleware_automation-wildfly-*.tar.gz

  ci:
    uses: ansible-middleware/github-actions/.github/workflows/ci.yml@rootperm
    secrets: inherit
    with:
      fqcn: 'middleware_automation/wildfly'
      root_permission_varname: 'wildfly_requires_become'
      molecule_tests: >-
        [ "default", "prospero", "yaml_config_validation", "install_options", "colocated_cluster", "custom_config_file", "custom_config_file_online", "temurinjdk_support", "app_deploy_standalone", "migration", "uninstall" ]
