---
name: Documentation
on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'

jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.repository == 'ansible-middleware/wildfly'
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      packages: write
      pages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/middleware_automation/wildfly
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install doc dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ansible_collections/middleware_automation/wildfly/docs/requirements.txt
          #pip install -r ansible_collections/middleware_automation/wildfly/requirements.txt
          sudo apt install -y sed hub

      - name: Create default collection path
        run: |
          mkdir -p /home/runner/.ansible/collections/ansible_collections

      - name: Create changelog and documentation
        uses: ansible-middleware/collection-docs-action@main
        with:
          collection_fqcn: middleware_automation.wildfly
          collection_repo: ansible-middleware/wildfly
          dependencies: false
          commit_changelog: false
          commit_ghpages: true
          changelog_release: false
          generate_docs: true
          path: ansible_collections/middleware_automation/wildfly
          token: ${{ secrets.GITHUB_TOKEN }}
