---
name: Release collection
on:
  workflow_dispatch:

jobs:
  release:
    uses: ansible-middleware/github-actions/.github/workflows/release.yml@main
    with:
      collection_fqcn: 'middleware_automation.wildfly'
      downstream_name: 'eap'
    secrets:
      galaxy_token: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
      jira_webhook: ${{ secrets.JIRA_WEBHOOK_CREATE_VERSION }}
